version: "3.7"

services:
  postgres:
    image: postgres:12.3
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER-test}
      POSTGRES_PASSWORD: ${PG_PASS-test}
      POSTGRES_MULTIPLE_DATABASES: "imagerec, imagerectest"
      POSTGRES_SCHEMAS: "imagerecognition"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - "./create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.14.0
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Edge Proxy
    environment:
      - SERVICES=sns,s3
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

volumes:
  localstack-vol:
  postgres-vol: